#ifndef MSSCENEDEF_H__
#define MSSCENEDEF_H__

namespace MSRPC
{
	enum ITEM_DATA_KEY { IDK_USERDATA, IDK_NAME, IDK_TRANSFORM, IDK_PIXMAP, IDK_SVG, IDK_EXTATTR };

	enum TRANSFORM_KEY { TK_TRANSLATE, TK_SCALE, TK_ROTATE, _TK_TOTAL_ };
}


#endif // MSSCENEDEF_H__
