#ifndef MSSCENEDEF_H__
#define MSSCENEDEF_H__

namespace MSRPC
{
	enum ITEM_DATA_KEY { IDK_NAME, IDK_TRANSFORM, IDK_PIXMAP, IDK_SVG, IDK_PPATH, IDK_CUSTOM };

	enum TRANSFORM_KEY { TK_TRANSLATE, TK_SCALE, TK_ROTATE, _TK_TOTAL_ };

	enum PAINTERPATH_KEY { PK_MOVETO, PK_LINETO, PK_QUADTO, PK_CUBICTO, PK_ARCMOVETO, PK_ARCTO, _PK_TOTAL_ };
}


#endif // MSSCENEDEF_H__
